### ISSUE TITLE
Header & Footer logos black on trac when large screen

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-mu-plugins#164]
The recent template changes (#160 & c5d7bee250946527723b0f3960932b087247c538) need to be synced over.

View any trac, with a browser wider than 1440px. The logo is black on black.

<img width="517" alt="Screen Shot 2022-02-16 at 6 54 33 PM" src="https://user-images.githubusercontent.com/541093/154377325-e08c5dce-5d35-40cd-8ae1-ed387d9719f0.png">

**Comment by iandunn** [comment]
Looks like [it's happening on Profiles too](https://meta.trac.wordpress.org/ticket/6115)

**Comment by NekoJonez** [comment]
Yeah, I opened a meta trac ticket for it: https://meta.trac.wordpress.org/ticket/6115

**Comment by ryelle** [comment]
@iandunn how is the header generated there? I thought it was loaded from an API endpoint? (related, just opened #165 to get this all written down somewhere)

**Comment by iandunn** [comment]
Since Profiles is a WP site, the block is just rendered like on any other site. i.e.,

```php
echo do_blocks( '<!-- wp:wporg/global-footer /-->' );
```

But, because it's not on the w.org network, `get_global_styles()` fetches them via the endpoint rather than `switch_to_blog()`.

https://github.com/WordPress/wporg-mu-plugins/blob/6f79c16423ba7432c30eb7460bd61531d6909029/mu-plugins/blocks/global-header-footer/blocks.php#L897-L904

`r18316-dotorg` shows how it was added.

**Comment by NekoJonez** [comment]
Also, on profiles it only looks like its the footer. The header logo looks fine to me.

**Comment by ryelle** [comment]
I just redeployed and I think that fixed it — @NekoJonez how does it look now?

**Comment by NekoJonez** [comment]
Very fixed! 
Somebody should close the trac ticket then too....? Or should I do that @ryelle ?

**Comment by ryelle** [comment]
Great! I'll close the trac ticket too.
