### ISSUE TITLE
Header looking different in "Get Involved" section 

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-mu-plugins#185]
Currently, the header fonts sizes in "Get Involved" look much smaller than in other pages. I see this happening in Safari, not other browsers.

https://user-images.githubusercontent.com/65220155/158198496-d7bf4b46-9e0a-427f-a488-0a0454af99b4.mp4

**Comment by iandunn** [comment]
🤔  I'm having trouble reproducing this using Safari `15.4 (17613.1.17.1.6)`

Do you see it @StevenDufresne or @renintw ? If so, can you tell which stylesheet and rule is overriding the header's stylesheet?

I'm guessing whatever is causing the problem is coming from wp4.css or the Make theme's stylesheet, but I don't see anything in the latter that would apply, and the former would probably affect other classic themes.

**Comment by ryelle** [comment]
@beafialho By any chance, is your browser zoomed out a little for `make.w.org` sites? It looks like the admin bar text is also smaller on the Get Involved section.

**Comment by beafialho** [comment]
@ryelle thanks, in fact it seemed to be zoomed out, so issue solved. Is it not supposed to look the same in every page when I zoom in or out?

**Comment by ryelle** [comment]
I think by default browsers use the domain to know how to apply the zoom across sites, and the Get Involved section is `make.wordpress.org` while the other pages are `wordpress.org`. So the zoom probably persists across all the make sites, but not up to the rest of the sites. Is that what you meant?
