### ISSUE TITLE
Header: in-page link targets are covered by header

### ISSUE THREAD

**Issue by joyously** [WordPress/wporg-mu-plugins#219]
Now that the new header had fixed position, links to targets are hidden under it. 

On a Make site, click on a sidebar link to a comment, for example, [Matt's comment](https://make.wordpress.org/design/2022/07/08/project-kickoff-wordpress-org-homepage-and-download-page-redesign/#comment-26507). 
Note that you have to scroll to find the start of the comment.

You can add CSS for this (use the height of the header)
`[id] { scroll-margin-top: 2em; }`

**Comment by iandunn** [comment]
We do have something like that already:

https://github.com/WordPress/wporg-mu-plugins/blob/01e6ca252a72186aa783ec3551f2fa8f750b9ad2/mu-plugins/blocks/global-header-footer/postcss/common.pcss#L29

It works for me when I'm logged out, but not when logged in. Both have admin bars. It may be that the code assumes that logged-in sites don't have the admin bar, which [recently changed on some sites](https://wordpress.slack.com/archives/C02QB8GMM/p1657368694801329).

**Comment by joyously** [comment]
That's not the same thing, since it's on `html` and not on `[id]`, _and_ in a media query.

**Comment by iandunn** [comment]
It's in a media query because the header isn't `fixed` on mobile. 

https://github.com/WordPress/wporg-mu-plugins/blob/433d57f3b7f679c0585836ac81375814472bcd1e/mu-plugins/blocks/global-header-footer/postcss/header/header.pcss#L27-L28

I haven't looked into targeting `html` vs an ID, though, that might be part of it 👍🏻

**Comment by iandunn** [comment]
Disabling the `logged-out-admin-bar` plugin doesn't fix it. IIRC it worked fine at launch, so if it's not the `html vs id` issue, it could be a recent change in Gutenberg.

**Comment by ryelle** [comment]
I think the issue here is limited to Make sites, and there's some kind of scrollTo JS in p2 that overrides the `scroll-padding-top` offset that works on other sites.

For example, [this anchor on developer.w.org works](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#space-usage), but [this one on another make site doesn't](https://make.wordpress.org/core/2022/10/10/miscellaneous-editor-changes-for-wordpress-6-1/#start-content-patterns-for-all-post-types).

**Comment by joyously** [comment]
I tried both of your links and they both have the problem. The developer one was worse for me than the Make one.
Clicking the first link shows me (Firefox):
![PHP Coding Standards Coding Standards Handbook WordPress Developer Resources-38](https://user-images.githubusercontent.com/7957680/195633744-c17af6c3-dcbd-4a74-a4ac-e85264009cfa.jpg)

Scrolling up a little shows how far off it was:
![PHP Coding Standards Coding Standards Handbook WordPress Developer Resources-30](https://user-images.githubusercontent.com/7957680/195633837-df6b06d7-fec1-425c-a534-890752a5d785.jpg)

The second link shows me:
![Miscellaneous editor changes for WordPress 6 1 – Make WordPress Core-53](https://user-images.githubusercontent.com/7957680/195633907-4930dfbc-5f91-4db1-9376-b9f84032ce29.jpg)

Scrolling up (less than the other one):
![Miscellaneous editor changes for WordPress 6 1 – Make WordPress Core-07](https://user-images.githubusercontent.com/7957680/195633996-a63a0c0f-0426-47ef-920f-82f33ffa7911.jpg)

**Comment by ryelle** [comment]
Oh interesting, that's correct — in-page anchors work, so on Developer, if you use the side table of contents to navigate to section, it works as expected. Same with the list of links in the make dev note. But direct links to page content don't work.

**Comment by adamwoodnz** [comment]
This appears to be fixed [now that the global header is no longer sticky](https://github.com/WordPress/wporg-mu-plugins/pull/466). I've tested all the links in the comments on this issue.

Let me know if this is not the case.
