### ISSUE TITLE
Reconfigure the site navigation

### ISSUE THREAD

**Issue by critterverse** [WordPress/wporg-mu-plugins#251]
There's a discussion happening on the [Make Meta blog](https://make.wordpress.org/meta/2022/08/18/navigation/) as the moment about the WordPress.org site navigation being a bit of an unorganized mess. 

### Current navigation:

<img width="1600" alt="current-desktop" src="https://user-images.githubusercontent.com/77359364/186693491-55f3f4bd-9662-4931-8bf8-e0ecda086370.png">

<img width="1600" alt="current-mobile" src="https://user-images.githubusercontent.com/77359364/186693502-40c39e93-a4c7-4d4b-b478-b0552a06da76.png">

There have already been a lot of great suggestions about how to reorganize things in the comments of the Meta post — I tried to capture some of those ideas in the proposal below.

### Proposed changes:

<img width="1600" alt="proposed-desktop" src="https://user-images.githubusercontent.com/77359364/186695153-7b54d7da-e348-4c5e-b494-495ef8a89394.png">

<img width="1600" alt="proposed-mobile" src="https://user-images.githubusercontent.com/77359364/186695947-e9339823-cbf0-4d1b-b314-1197b3e4a7a5.png">

Some notes:

- We could reduce down to six main menu items with one submenu for the “Create” section only — this is up for discussion and possibly not needed, especially if the sublinks appear in the footer and on the main Create page
- We could save some space by never showing the full WordPress.org logo lockup — the logo could always appear as just the "W"
- With this overall simplication, it would be great to make the top-level pages more like landing pages that contain links to many different sub-sections (possibly through an inline sub-navigation system)

---

In case it's easier to read, here's the nav structure shown above in list form:

**News**
_Landing page for Release, People of WordPress, etc_

**Create**
_Landing page for editor/Gutenberg page, extendability, etc_
- Submenu for Create: **Plugins, Themes, Patterns, Photos, Openverse**

**Community**
_Landing page for Events, Contributing, etc_

**Support**
_Landing page for Documentation, Learn WordPress, etc_

**Five for the Future**

**About**
_Landing page for Showcase, Requirements, Features, Philosophy_

---

Thanks to @javierarce and @jasmussen for weighing in. Would love to hear everyone's thoughts, especially in regards to what we could ship quickly as a v1 improvement on the current nav system.

Figma: https://www.figma.com/file/SQwX90pGxS0XlNTEyNhDRE/WordPress.org-Navigation-Explore?node-id=2%3A1965

**Comment by ryelle** [comment]
FYI, moving this & WordPress/wporg-mu-plugins#252 to the `wporg-mu-plugins` repo since that's where the header lives.

**Comment by juanmaguitar** [comment]
I shared my proposal [here](https://make.wordpress.org/meta/2022/08/18/navigation/#comment-9405) and also shared [a diagram](https://excalidraw.com/#json=RfxvGY4lQv21b8dailrcv,k5EB68urjyinivOc8Qd5TQ) with my proposal

There are two main things I'd like to highlight from it:
- The use of verbs (as much as we can) to better connect the audience with the different points of information (_Get WordPress, Discover, Learn, Get Involved..._ )
- Grouping all the resources involved in the Learning Experience of WordPress under a generic **Learn** category (_Documentation, Courses, Forums, WordPress TV, Developers..._)
  - I think learn.wordpress.org should point to a landing page with all the resources to learn or solve issues about WordPress (actually it points only to a courses/tutorial section).

**Comment by eidolonnight** [comment]
A few marketers attempted, as best we can, to combine the ideas of the [open discussion ](https://make.wordpress.org/meta/2022/08/18/navigation/) into a single table below. During this process, we documented a few guidelines in order to remain relatively consistent in our approach now and in the future. That said, the resulting recommendation is based on the site structure as it is _now_. This solution can be implemented without the creation of additional pages.

- This approach groups pages by visitor intent. Example: “I’m here to build out my site” or “I’m here to participate in the project”.
- To keep things slim, this approach directs visitors to top-level pages or areas where they can dig deeper rather than trying to deep-link visitors to everything. Example: Link to "Learn" rather than "Tutorials" and/or " "Lesson Plans".
  - There is a footer menu to help surface some key pages that perhaps don't fit in the main nav.
- Top-level items are organized based on the frequency of visits. “About” might be most used by new visitors, but “News” will be used repeatedly by visitors every day.
  - Child items were generally sorted by broadest appeal (Ie. most visits) to least.
- Link names should be accessible and recognizable to everyone. “Contribute” may be readily recognizable to existing community members, but alternatives like “Community” are more easily understood by everyone.
- Parent items link to logical existing pages and also describe child items.

_Note: Table header represents parent menu items with each column containing the respective children._

| [News](https://wordpress.org/news/)  | [Download & Extend](https://wordpress.org/download/) | [Learn](https://learn.wordpress.org/) | [Community](https://make.wordpress.org/) | [About](https://wordpress.org/about/)
| ------------- | ------------- | ------------- | ------------- | ------------- |
|  | [Themes](https://wordpress.org/themes/)  | [Support](https://wordpress.org/support/)  | [WordCamp](https://central.wordcamp.org/)  | [Showcase](https://wordpress.org/showcase/)  |
|  | [Patterns](https://wordpress.org/patterns/)  | [Forums](https://wordpress.org/support/forums/)  | [Meetups](https://www.meetup.com/pro/wordpress/)  | [Gutenberg](https://wordpress.org/gutenberg/)  |
|  | [Plugins](https://wordpress.org/plugins/)  | [WordPress.tv](https://wordpress.tv/)  | [Photo Directory](https://wordpress.org/photos/)  | [Enterprise](https://wordpress.org/enterprise/)  |
|  | [Openverse](https://wordpress.org/openverse/)  | [Developers](https://developer.wordpress.org/)  | [Job Board](https://jobs.wordpress.net/)  |  |
|  | [Mobile](https://wordpress.org/mobile/)  |  | [Five for the Future](https://wordpress.org/five-for-the-future/) |  |
|  | [Hosting](https://wordpress.org/hosting/)  |  |  |  |

**Additional notes**

- News is large enough, and updated frequently enough, that it deserves a space within the main navigation. This is a powerful signal to visitors and search engines. That said, if space is limited, it could just as easily live under "About".
- Forums are technically a sub-section of Support, but it is currently hidden at the bottom of the Support hub page. Especially in the case of learning and support, the barrier to entry should be low. The forums are also some of the highest trafficked pages, so reducing clicks to get there makes sense.

**Comment by critterverse** [comment]
Mockup for @eidolonnight's suggestion:

![wp-org-nav](https://user-images.githubusercontent.com/77359364/186932548-48e93026-577e-419e-9674-a64f2554e630.gif)

**Comment by ryelle** [comment]
> We could save some space by never showing the full WordPress.org logo lockup — the logo could always appear as just the "W"

For what it's worth, the "WordPress.org" text only shows up at 1440px wide, so I don't think we need to remove it to save space. With even fewer top-level items, 1440 has the space for it :) But if it's a matter of looking busy, it can be removed entirely. What do you think, @critterverse?

**Comment by critterverse** [comment]
>But if it's a matter of looking busy, it can be removed entirely.

^ Yeah, I think this is also part of it. Let's make this change across all sizes if that works!

**Comment by bengreeley** [comment]
Thank you for your work on this @critterverse! Something that comes to mind as possibly needing to be revisited is the 'Photos Directory' link might make more sense under 'Download & Extend' since it's a utility similar in functionality to Themes, Plugins and Patterns as the photos are for extending and building WordPress websites.

**Comment by thetinyl** [comment]
@bengreeley This is a really good point. The WP Photo Directory feels like it could fit in both the 'Download & Extend' and 'Community' submenus. The former, for the reason you mentioned, and the latter because it's managed and populated by contributors (and a fun and easy way for newcomers to start getting involved). 

@eidolonnight can confirm this, but since Photo Directory images do appear in Openverse search queries, putting the Photo Directory under 'Community' feels like a possible way to call attention to it without seeming like duplication.

**Comment by eidolonnight** [comment]
Yes, as @thetinyl mentions, we have both [Openverse](https://wordpress.org/openverse/) and the [Photo Directory](https://wordpress.org/photos/) present in the menu. Remember:

> This approach groups pages by visitor intent. Example: “I’m here to build out my site” or “I’m here to participate in the project”.

Openverse is focused on consumption, searching for images and audio you can use while building your site. It's an easy fit for Download & Extend.

Meanwhile, the Photo Directory is a curated area (thanks to the Photos team) that is very much a mechanism for contributors to submit images that can be found there and in Openverse. Example:
- [This image in the Photo directory](https://wordpress.org/photos/photo/2576290cde/)
- [Also appears in Openverse](https://wordpress.org/openverse/image/383d2106-393b-4303-b0a6-3e88db10f286)

Therefore, the Photo Directory seems to best fit under Community with the various other options for visitors to get involved with the project.

**Comment by juanmaguitar** [comment]
> With this overall simplication, it would be great to make the top-level pages more like landing pages that contain links to many different sub-sections (possibly through an inline sub-navigation system)

I'd like to highlight this comment from @critterverse as I completely agree with this.
I think the combination of the proposed menu with landing pages would have a huge positive impact on the learning experience of users on the site

From my POV this idea of having a landing page per "section", shouldn't be a blocker for the first release of the menu with the proposed organization (could be done later in a "second phase"), but I'd like to know more thoughts about this and if there are any plans to work on this in the close future.

**Comment by SchneiderSam** [comment]
Love this rework! I think it's important to speak a clear language in the menu. „Five for the Future“ is so abstract, and I think that defeats its purpose. I think expressions like „Contribute“ are much better.

**Comment by SchneiderSam** [comment]
> we have both [Openverse](https://wordpress.org/openverse/) and the [Photo Directory](https://wordpress.org/photos/) present in the menu

I find it kind of irritating. why not unify everything? Both have images, but they are somewhat different. Hmm. from user point of view not very clear...

**Comment by colinchadwick** [comment]
I just wanted to show a part of my redesigned navigation here. A mega menu would clean up the navigation even more, but without confusing people. It gives a lot of space for explanations, images and more. This one is inspired by Webflow, but I tried to adapt it to the new snappy look of WP.org.

In general, I feel like people working with WordPress these days aren't that technical anymore. They just want things to work. For this reason, presenting features in a simple list is not really effective. WordPress has so many great features, but some of them don't get used, not because they're bad, but because they're not presented in an easily accessible way.

![570F274C-FCCE-4F00-BBF8-097D984FE53E](https://user-images.githubusercontent.com/62803839/187416110-fbef3cc5-4992-4fd8-bd2e-b0cb7ee6639c.png)

**Comment by critterverse** [comment]
Thanks for sharing @colin-chadwick, I really like your idea!

As next steps, I think we should move forward with changes to the navigation structure using the existing UI so we can get those updates live as quickly as possible. From there, it would be great to discuss where folks think we should head next — consolidated landing pages or expanded mega menus both seem like really interesting options to explore. 

If we do want to consider a consolidated landing page route in the future, I can imagine picking one section to try out that approach as an MVP (perhaps Learn?)

**Comment by iandunn** [comment]
From #34:

<blockquote>
The menu now has so many links that we need to use a "overflow" script (see #21). Folks have discussed an IA refactor, including the following rough ideas

### Header

- [ ] add blocks. they're in the plugins section already, but that's not obvious
- [ ] add openverse - maybe as "images" rather than "openverse". maybe both "add-ons > images" and then "tools > openverse"
- [ ] group plugins/themes/blocks/patterns/images under 1 top "add-ons" / "resources" / "extensions" ?
- [ ] Moving Showcase, Mobile, and Hosting pages out of the header, or move into submenus. Showcase could go under About; Mobile and Hosting could go under Resources. Maybe convert the Get WP button to a regular menu, which has "hosting", "download", and "mobile" as subitems
- [ ] Direct access to internal pages of sections Learn and Support.
- [ ] add WordPress.TV? Browse Happy? bbPress and/or BuddyPress?
- [ ] add Developer tools like WP-CLI?
- [ ] something for plugin/theme devs, since that’s such a fundamental part of the ecosystem. maybe a submenu item for https://developer.wordpress.org/, or even a Developers top-level section.
- [ ] Maybe add an “Community” menu, w/ WordCamps, meetups, Learn discussion groups etc?

### Footer

- [ ] add labels to each column so it's clear how they're organized
- [ ] add mobile, since it's in the header
- [ ] add openverse
- [ ] add blocks
- [ ] add wp-cil
- [ ] add meetups
</blockquote>

IIRC @beafialho and @pablohoneyhoney have mockups for a mega menu as well.

**Comment by ryelle** [comment]
Just confirming since discussion continues here — we're going to implement the menu described [in this comment](https://github.com/WordPress/wporg-mu-plugins/issues/251#issuecomment-1228545353), as-is, and iterate on that (and the suggested landing page idea) in the future. 

I've removed the "In Discussion" label so this is ready for a dev to pick up.

**Comment by jomarieminney** [comment]
The new menu has a glaring gap in that it is almost impossible to find information on contributing unless you already know what five for the future is/means, and even then it still requires hunting. I have tested this with several user groups. Also I made multiple attempts to comment on this to suggest approaching it using best practice UX techniques (eg. Card mapping) but none were approved on the Wordpress post. This revised navigation is done with the best of intentions but zero actual data or best practise processes followed. I’d strongly recommend some tree testing be conducted at WCUS to identify glaring usability gaps.
