### ISSUE TITLE
Simplifying the wp-admin bar that appears above the site navigation

### ISSUE THREAD

**Issue by critterverse** [WordPress/wporg-mu-plugins#252]
There's a discussion happening on the [Make Meta blog](https://make.wordpress.org/meta/2022/08/18/navigation/) as the moment about the WordPress.org site navigation being a bit of an unorganized mess. Some of the issues have to do with the wp-admin bar that appears above the navigation:

- This bar duplicate the logo, showing it twice in close proximity
- The colors and styles feel different from the rest of the components on the site
- It has a totally separate dropdown menu that feels hidden/not integrated well with the main navigation of the site

I have a few suggestions to clean up and better integrate this UI.

### Homepage — logged out

<img width="1600" alt="home-logged-out" src="https://user-images.githubusercontent.com/77359364/186704632-cf7b0fe7-bb80-4642-855a-24b08c267fd6.png">

- It would be great to show the admin bar on the homepage even when logged out
- The admin bar and associated menus could be re-styled to match the typography, color, spacing of the rest of the site.
- For the logged out state, we could hide several items that current appear including the W logo and the search. This would leave two links on the right hand side to Register and Log in.

### Homepage — logged in

<img width="1600" alt="home-logged-in" src="https://user-images.githubusercontent.com/77359364/186704667-bef04d18-9b00-445c-ad71-6354b5bce902.png">

- For the logged in state, we could incorporate the "My Site" links into the existing (re-styled) user profile menu that's accessible from the upper right.
- The "W" logo and search would be hidden in this view (same as the logged out state).

### Subpages

<img width="1600" alt="subpage-logged-in" src="https://user-images.githubusercontent.com/77359364/186704742-7c8a3e6b-9fe0-475d-86e3-3b841e6369ee.png">

- The logged out state for homepage could be the exact same as the homepage
- When logged in, we might want to show an action/menu for creating new items in the upper left. Any other post management actions can take place by navigating to that site from the user menu.

For future iterations, it would be cool to look at how to more fully integrate the wp-admin bar into the navigation. There are a lot of different things that could be explored, such making a state change that would display the user info more prominently when logged in:

| Possible future integration (logged out) | Possible future integration (logged in) |
| ------------- | ------------- |
| <img width="1600" alt="future-logged-out" src="https://user-images.githubusercontent.com/77359364/186701014-2d6eb70c-77b0-4420-be65-4d33d8a1511c.png"> | <img width="1600" alt="future-logged-in" src="https://user-images.githubusercontent.com/77359364/186700937-ef8f6be3-1116-4151-8344-3b605b4b0d49.png">  |

Would love to hear your thoughts! Thanks @javierarce and @jasmussen for collaborating on this proposal.

Figma: https://www.figma.com/file/SQwX90pGxS0XlNTEyNhDRE/WordPress.org-Navigation-Explore?node-id=2%3A1965

**Comment by SchneiderSam** [comment]
I think it's important to speak a clear language in the menu. „Five for the Future“ is so abstract, and I think that defeats its purpose. I think expressions like „Contribute“ are much better.

**Comment by SchneiderSam** [comment]
> Would love to hear your thoughts!

Amazing work. Thanks so much for working on this!

> Possible future integration (logged in) image

THIS is sooo cool. Clean and easy. Why not use the same principles for the logged out mode? Something like this:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/9355398/187370291-fc0467b8-aa31-4a2a-9144-e9adc0e935e3.png">

Instead of two menus, we use only one menu. The login link is right next to the download button. Nice and simple and clear.

**Comment by MahdiEbrahimii** [comment]
this sooo cool 
We will see a good change

**Comment by Otto42** [comment]
Why is the admin bar back on the homepage?

The wordpress.org homepage is explicitly not supposed to have an admin bar for non logged in users. 

Since this addition, there has been numerous problems that have cropped up with people not understanding why we have a register and login link there. 

The most notable example is that registrations have increased because people think they have to register to use WordPress. I had one example of a guy who created three different logins because he's thought he had to register for each separate WordPress site he was creating. He was literally creating a different login for every test site he made. These weren't even live sites.

WordPress is free to use for all users. Implying that registration is required is not what we want to have. The only reason to register is if you're going to use the support forms, or trac, or be a plugin or theme author. We're getting about 100 emails a day from registration problems because of this issue. They have a form letter now that they send to every person who requests help which basically says "you don't need to register to make a WordPress site".

Please revert this change immediately and remove the admin bar for logged out users from the WordPress home page. It also should not be shown on the download page, or pretty much any of the pages that are relatively static and unchanging on wordpress.org.

**Comment by iandunn** [comment]
Related https://github.com/WordPress/wporg-mu-plugins/issues/128

**Comment by Otto42** [comment]
Has anything been done about this? We are getting hundreds of emails per day. The confusion is real.

**Comment by iandunn** [comment]
9b8c92e37794fde24c957e8d48dcc663fe2dea6e hides it on `/` and `/download`.

**Comment by Otto42** [comment]
@iandunn Thank you for that. Now, can we get it removed from the international home pages as well? All that has really changed is now all of the emails we get are primarily in different languages.

**Comment by iandunn** [comment]
Added those in 0ffa239 👍🏻
