### ISSUE TITLE
Submenu hover issue on bigger touch devices   

### ISSUE THREAD

**Issue by colinchadwick** [WordPress/wporg-mu-plugins#261]
Hovering (touching) submenu links on bigger touch devices causes the page to load the parent link, preventing users from choosing a page from the submenu dropdown.

https://user-images.githubusercontent.com/62803839/188175622-50edae82-ee9f-4403-b2bf-bf7eca3a3cc8.MOV

**Comment by ryelle** [comment]
There's an arrow next to each item that should open the submenu, but the tap target is very small. That was mentioned in #249, so the fix there should fix (or at least help) here. Changing the behavior of that top-level link would need to be a Gutenberg issue though, since this menu uses the Navigation block.
