### ISSUE TITLE
Search: Mobile overlay does not properly lock the screen in place

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-mu-plugins#371]
Demo video: 

https://user-images.githubusercontent.com/25516611/227920703-11194390-3aab-49df-8617-08403b80cdaf.MOV

This appears to be an upstream Gutenberg issue (I'll ticket separately), but worth fixing locally in the meantime. When the navigation block opens an overlay, a CSS class gets applied to the HTML element:

```
html.has-modal-open {
    overflow: hidden;
}
```

As best I recall, this used to be sufficient to prevent Mobile Safari from scrolling the parent content, but it appears not. We should see if additional fixes would address this, perhaps:

```
html.has-modal-open {
    overflow: hidden;
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}
```

☝️ I will separately vet whether that fixes it, and follow up.

**Comment by jasmussen** [comment]
Yes, it appears that adding `position: fixed;` to the overlay fixes this issue. Before:

<img width="600" alt="Screenshot 2023-03-27 at 13 49 41" src="https://user-images.githubusercontent.com/1204802/227933680-c7d433fe-40d0-45fb-8d6b-be45c53cffe9.png">

After:

<img width="600" alt="Screenshot 2023-03-27 at 13 50 51" src="https://user-images.githubusercontent.com/1204802/227933695-7918b123-7061-4685-82d7-dcf672734a2d.png">

<img width="316" alt="Screenshot 2023-03-27 at 13 50 58" src="https://user-images.githubusercontent.com/1204802/227933713-6d15f41f-7b90-4cdb-aab0-1f87097858ec.png">

**Comment by jasmussen** [comment]
Upstream followup: https://github.com/WordPress/gutenberg/pull/49369

**Comment by iandunn** [comment]
#381 ended up having some unintended consequences, but I think I'm on a better path with #382. It still needs more testing, though.

FYI @jasmussen in case any of that impacts your upstream PR. I needed to set `<html>` back to `position: static`, but that's probably just a result of how we're using the Nav block in an unexpected way. It may still be good to apply `position: fixed` to the breakpoints where the modal is expected to be used, though. 

It might also be worth experimenting with some of the styles in #382 instead, since that might preserve the scrolling position. I haven't tested that, though, it's very possible that those styles are worse for a standard theme.

**Comment by ryelle** [comment]
@iandunn Are you still working on this, or did you want another dev to take a look at #381 & #382?

**Comment by iandunn** [comment]
I paused working on it because launching WP20 became a higher priority. I was planning to circle back once there's nothing left for me to do there, but I don't mind if someone else wants to pick it up in the meantime.

**Comment by ryelle** [comment]
Some more details — this is happening only on the search modal and only when the keyboard is open. It sounds like this is something of a known issue with iOS, that opening the keyboard forces a scroll on the page. I found this article, [The Eccentric Ways of iOS Safari with the Keyboard](https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d), the problem description is good though the "solutions" aren't really applicable to us.

That said, in my testing, `position: fixed` does seem to work — there's still a little scroll with the search modal + keyboard, but it doesn't show the page content behind it.

@iandunn What issues were you seeing with the `position: fixed` approach?

**Comment by iandunn** [comment]
I think it was this:

https://github.com/WordPress/wporg-mu-plugins/blob/36079b27dc23d29c1e53c353eb09fc6aaba068d0/mu-plugins/blocks/global-header-footer/postcss/header/header.pcss#L24-L28

IIRC that only happens because we're using the Nav block in an unexpected way, where the modal is open on desktop views for the search block.

https://github.com/WordPress/wporg-mu-plugins/blob/482d0c7a1349ce140b6879b35aabf12c067cfb8c/mu-plugins/blocks/global-header-footer/header.php#L96-L103

**Comment by ryelle** [comment]
I saw that comment but couldn't replicate it, do you remember what browser you saw it on?

**Comment by iandunn** [comment]
It doesn't happen on all pages, but here's a few that I'm seeing. It looks like FF, Chrome and Safari all show it.

![Screenshot 2023-04-12 at 11 06 57 AM](https://user-images.githubusercontent.com/484068/231546019-2f45cccd-8595-4abc-9756-4f10ea068cea.png)
![Screenshot 2023-04-12 at 11 07 31 AM](https://user-images.githubusercontent.com/484068/231546109-e7038165-ee98-4ce0-bc24-e04bc59fdb94.png)
![Screenshot 2023-04-12 at 11 08 28 AM](https://user-images.githubusercontent.com/484068/231546300-ee822205-38ad-49a3-a921-e391b1a868c9.png)

I also noticed:
![Screenshot 2023-04-12 at 11 08 08 AM](https://user-images.githubusercontent.com/484068/231546236-7dc86915-6beb-42a2-9bf7-58ef383bf900.png)
