### ISSUE TITLE
Mobile menu trigger displayed on profiles.wordpress.org

### ISSUE THREAD

**Issue by alexstine** [WordPress/wporg-mu-plugins#405]
On a single profile such as https://profiles.wordpress.org/alexstine/, the "Open menu" trigger is available for screen readers. This seems to not be an issue on the rest of the site so not sure what is causing it here. It should not be visible for desktop viewports.

While testing in Firefox, the menu can actually gain focus on page load. This is a serious regression coming from somewhere. Not sure if its Gutenberg or custom code.

Trigger button:
```
<button aria-haspopup="true" aria-label="Open menu" class="wp-block-navigation__responsive-container-open always-shown" data-wp-on--click="actions.core.navigation.openMenuOnClick" data-wp-on--keydown="actions.core.navigation.handleMenuKeydown"><svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="4" y="7.5" width="16" height="1.5"></rect><rect x="4" y="15" width="16" height="1.5"></rect></svg></button>
```

On initial Firefox load, focus gets placed here.
```
document.activeElement

<a class="wp-block-navigation-item__content" href="https://wordpress.org/news/">Click to select the node in the inspector
```

CC: @ryelle

**Comment by ryelle** [comment]
> the "Open menu" trigger is available for screen readers.

It looks like this is actually the search modal trigger, but hack we used to update the button's label is not working anymore.

> While testing in Firefox, the menu can actually gain focus on page load.

I had this happen to me once, but then not again. There's another issue about the menus being broken in general: https://meta.trac.wordpress.org/ticket/7068 — I'm hoping they're both caused by the same thing, a JS error triggering from the Gutenberg code.

Aha, this site uses a different version of Gutenberg than the rest of the wordpress.org network, that's why it's only broken here.

I'll see what I can do about fixing the compatibility here.

**Comment by ryelle** [comment]
@alexstine I've deployed a fix that corrects the search button label (and fixes some visual regressions that were reported elsewhere), but I haven't been able to replicate the focus bug. Can you let me know if you're still encountering it?

**Comment by alexstine** [comment]
@ryelle Seems to all be working again. Thanks for the quick resolution here. I'll open further issues if I spot anything else.
