### ISSUE TITLE
Add "Blocks" page to Extend menu

### ISSUE THREAD

**Issue by annezazu** [WordPress/wporg-mu-plugins#417]
As work continues to add a Blocks page https://github.com/WordPress/wporg-main-2022/issues/245, I wanted to kick off an issue for adding it under the Extend menu once it's live. cc @jasmussen and @ndiego.

**Comment by jasmussen** [comment]
Indeed! What's blocking us from moving forward here? As I see it, the next steps could be:

* Change the top navigation to open submenus on click instead of hover
* Rename "Download & Extend" to "Extend", this is discussed separately, but Download is already a top level item, and linked in countless CTAs, it doesn't need to be duplicated here.

I'd love to see us move forward here.

**Comment by ndiego** [comment]
@jasmussen would you be ok with an initial step of just adding "Blocks" below "Plugins" in the existing nav? This would allow us to close out the Blocks page i1 project. This minor change would look like this, and I can have a PR completed shortly: 

<img width="599" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/42e88f0f-e229-4bf0-b105-722069e05b66">

Then separately, we can begin regrouping on the broader nav overhaul. I personally feel this can be tackled as its own project, which would be good to complete in conjunction with the Showcase redesign since the [current proposal](https://github.com/WordPress/wporg-mu-plugins/issues/360#issuecomment-1540133521) is for that to be a top-level link.

**Comment by jasmussen** [comment]
Sure, but I don't know that the navigation overhaul really needs to be a project per se, _ideally_ the "click to open" should be a toggle in the nav block, and the rename would be good too.

**Comment by annezazu** [comment]
@ndiego the page is now live http://wordpress.org/blocks!
