### ISSUE TITLE
Block: Query Filter: Filters are visible above navbar

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-mu-plugins#452]
Might be related to https://github.com/WordPress/wporg-mu-plugins/pull/449

The filter button and popup display above the header nav and local nav on scroll in [Showcase v2](https://wordpress.org/showcase-v2/). Should be a simple z-index fix. 🤞

<img width="929" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/1e0fcde3-78c4-46cc-a9fc-15661f0a051a">

**Comment by ryelle** [comment]
This might be tricky/not possible, because the overlay behind the dropdown (invisible here, visible on mobile) needs to be above everything to capture clicks outside the dropdown.

**Comment by ryelle** [comment]
If we move this layer behind the header, the header would still be interactive when the dropdown is open. That's different behavior than everything else on the site (the rest of the site would have the click-outside-to-close behavior before it's interactive). Is that okay?

**Comment by ndiego** [comment]
> If we move this layer behind the header, the header would still be interactive when the dropdown is open. That's different behavior than everything else on the site (the rest of the site would have the click-outside-to-close behavior before it's interactive). Is that okay?

Hmm, very good question. Any thoughts @jasmussen @marko-srb?

**Comment by jasmussen** [comment]
This is no different from a stock `select` box, is it? If yes, then it's fine. The thing is, we don't want to limit the scroll for these dropdowns, or even auto close on scroll, so we can only do so much.

**Comment by ryelle** [comment]
> This is no different from a stock select box, is it?

Not quite, an HTML select dropdown handles focus natively, so it doesn't need the z-index'd overlay to listen for outside click events (the perils of creating our own component). And since it doesn't need that overlay, it doesn't need have z-index, so it wouldn't have this issue.

When I was first building this, I followed some of the same code that's used for the navigation block dropdowns, which uses a different approach for listening for outside — it didn't totally work because the nav block expects only focusable children, but this block uses containers and such. Maybe it could be worth another look after launch? It would probably be complex though.

Or my previous suggestion— just move the z-index of this down under the header.

**Comment by ndiego** [comment]
> Or my previous suggestion— just move the z-index of this down under the header.

This is my vote for launch. It would make things look a lot better on desktop.

**Comment by jasmussen** [comment]
Yep, simplest path forward, let's go with that.
