### ISSUE TITLE
Improve the Register/Login experience on WordPress.org

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-mu-plugins#565]
There are sections of WordPress.org where the user may need to Register/Login to perform certain actions. Examples include [Forums](https://wordpress.org/support/forums/), [News](https://wordpress.org/news/), [Plugins](https://wordpress.org/plugins/), [Learn WordPress](https://learn.wordpress.org/), etc.

On these sites, the Register/Login appears in the top-right of the screen like this: 

<img width="1256" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/3901653f-3fef-46cf-b39f-ed5aa3f72f66">

The layout is not ideal and creates unnecessary extra space at the top of the page. How could we fix this?

Perhaps these links are integrated into the header? This would introduce other mobile issues that would need to be figured out 🤔

<img width="1254" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/c1256076-db17-4506-a361-4a3daa3525a4">

Removing this Register/Login bar when the user is logged out would also resolve https://github.com/WordPress/wporg-mu-plugins/issues/426

**Comment by dd32** [comment]
Having the Toolbar present, purely for login/register links is really a vestige of the previous design. 

One question I have for the proposed design here though; is whether the logged in state for **regular users** should continue to have the toolbar, or whether that should be combined with the header here too.

For example, a user who has no elevated access on the site will have this experience (Note, I've added a border to the toolbar for obviousness)

<img width="1208" alt="Screenshot 2024-02-02 at 9 10 02 am" src="https://github.com/WordPress/wporg-mu-plugins/assets/767313/e672f0f3-d108-4286-b43d-47ac99d0928b">

And in some classic themes, it seems they also get a link back to the current sites homepage, which for `/support/` will actually land them on `/documentation/`...

<img width="1211" alt="Screenshot 2024-02-02 at 9 11 30 am" src="https://github.com/WordPress/wporg-mu-plugins/assets/767313/4da58de6-4dbe-4771-9f7c-40720392e6ed">

I guess my question here; after changing the login links, are we then also going to want to combine the User menu into the header too?

For example; really badly styled.. _(edit: or probably to the left of the search icon, like your example of the Login/Register link)_

<img width="1280" alt="Screenshot 2024-02-02 at 9 16 25 am" src="https://github.com/WordPress/wporg-mu-plugins/assets/767313/c6466bdb-ccae-477f-88f1-9ad6bf6bb748">

_Edit: https://learn.wordpress.org/ also uses the Toolbar for a Locale Switcher_

**Comment by jasmussen** [comment]
When you're logged in, it seems fine to have the full adminbar. Agree when logged out it should not be there.

Integrating login/register into the main bar is an option, but it both comes with the tradeoff of consuming a great deal of space, and it becomes present on every single section. The last part, past feedback by, I believe, @Otto42 (see also [here](https://github.com/WordPress/wporg-mu-plugins/issues/252#issuecomment-1317936213)) suggests giving this level of prominence to the login/register buttons is a bad idea, because it causes people to sign up in droves thinking they have to in order to get WordPress.

To that end, a previous suggestion is to integrate the login better in every single section that needs one, with [this](https://github.com/WordPress/wporg-mu-plugins/issues/355) given as a previous example. That is, you only ever see your login/signup links in context of _where you need it_. 

Taking a fresh look today, here are my best instincts, and I welcome sanity checks and corrections for others that might have better insights in what is useful. Note, in the following review, I'm ignoring the adminbar login/signup links, and only looking at other links on the page.

Don't show:

* Homepage
* News (this assumes this doesn't have broad community access/contributors)
* Hosting
* Blocks
* About
* Enterprise
* Search
* Get WordPress

Has it, can be improved:

* Showcase: (header)
* Documentation: (in context of each page)
* Developers: this is unique in its GitHub integration, let's talk about this one

Has it, needs improvement:

* Themes: has it (Add your theme)
* Plugins: has it (Add your plugin)
* Patterns: has it (Submit your pattern)
* Learn: has it (Apply/submit)
* Photos: has it (Contribute)
* Five for the Future

Does not have it:

* Forums
* Make: maybe don't show on the index page?
* Make P2
* Events: doesn't have it, unclear it needs to

Depending on the feedback of the above, and considering the sections that do benefit from login/register links, my best suggestion would be to always keep a "Sign in" link as the last item in the secondary navigation bar, like so:

![Screenshot 2024-02-05 at 09 27 27](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/5504d5a4-bce1-4078-96ae-4bc24cf8b6b8)

This would be a pattern we can repeat across all the sections that should have the link. Just as an example in case we choose to update the Showcase for consistency and uniformity:
![Screenshot 2024-02-05 at 09 28 06](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/77d1191c-5411-4495-b129-4d3fff76d5df)

By being a single link, it is space efficient, and that single page can contain a "Sign up" link as well. There are [previous login page](https://www.figma.com/file/6KPZbXujMGDRWWDR5odjDE/WP.org-improvements-%2F-QA?type=design&node-id=21%3A1580&mode=design&t=BhhgGS76A6LJxC1M-1) mockups in the GH here, here with only small updates to the verbiage:

<img width="1120" alt="Log in flow" src="https://github.com/WordPress/wporg-mu-plugins/assets/1204802/9c88ad08-aa0b-4fb1-9b19-04ecae4fc3dd">

This single "Sign in" link we could show across themes, plugins, patterns, learn, photos, fftf, forums, make, make p2s, and events if need be, thus omitting the major sections where such a link would be confusing.

**Comment by courtneyr-dev** [comment]
I'm also interested in unifying the quantity of places teaching folks how to create profiles and connect to GitHub. I see many duplicates, but centralizing and focusing updates in a single place (Learn) seems most practical so that content isn't quickly outdated.

**Comment by ndiego** [comment]
Thanks for the discussion, folks. I am going to close this out in favor of [WordPress/wporg-mu-plugins#647](https://github.com/WordPress/wporg-mu-plugins/issues/647), which is more recent and provides additional information. Let's keep the discussion going over there!

**Comment by ndiego** [comment]
> I am going to close this out in favor of https://github.com/WordPress/wporg-mu-plugins/issues/647

Oops, forgot to actually close this 😅
