### ISSUE TITLE
Arrow aria-hidden applies in places it shouldn't

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#574]
As reported in https://meta.trac.wordpress.org/ticket/7466

> It seems the user input "→", the system wrapped it with `<span aria-hidden="true"></span>`, then it was included into `<meta name="description">` and `<meta name="og:description">` contents without being escaped.
> ```
> <meta name="og:description" content="ハンガーメニューの編集方法が分からず困っています。関連ありそうな部分としては外観<span aria-hidden="true">→</span>ウィジェットに&hellip;" />
> <meta name="description" content="ハンガーメニューの編集方法が分からず困っています。関連ありそうな部分としては外観<span aria-hidden="true">→</span>ウィジェットに&hellip;" />
> ```

This is actually affecting more things than just that specific page.
For example:
```
$ curl -is https://wordpress.org/plugins/ | grep '<span aria-hidden="true">'
<style>
.wp-block-wporg-google-map [...] .wporg-marker-list-item__title a:after{content:"<span aria-hidden="true">↗</span>";font-family:var(--wp--preset--font-family--inter) [...]
```
(Let's ignore that that CSS is enqueued on a page that would never use that block - and that on the only page it is used on, the CSS isn't being modified)

This is caused by #454, the filter would need to be altered to either filter the specific places the characters are used (ie. link names?) rather than the entire block, or, the regex made more specific to only match things outside of tags.

**Comment by ryelle** [comment]
> Let's ignore that that CSS is enqueued on a page that would never use that block - and that on the only page it is used on, the CSS isn't being modified

The CSS isn't modified on the page where wporg-google-map is used because the filter only applied to `head` code on classic themes.

I think the block styles are loaded here because it's technically rendering a classic theme, so it doesn't know which blocks are used, though I'm not totally sure about that. Adding `add_filter( 'should_load_separate_core_block_assets', '__return_true' );` removes them, but I'm not confident that it would then load correctly in the footer if the blocks were added to a classic page.
