### ISSUE TITLE
`Search` won't close when we click the `Close x` button

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-mu-plugins#92]
https://user-images.githubusercontent.com/65220155/148379859-25754158-766d-4f22-9335-04bb99587e2c.MP4

**Comment by ryelle** [comment]
Looks like this is a gutenbug, reported here: https://github.com/WordPress/gutenberg/issues/37996

**Comment by ryelle** [comment]
This was fixed in Gutenberg 12.5, which I think won't be released for another 2 weeks. But once the site is updated, we can re-test and close this issue.

**Comment by tellyworth** [comment]
Given that it's fixed upstream I think we should launch with it and close the issue once we've updated and tested to verify.

I think that means we should change the milestone to post-launch?

**Comment by dd32** [comment]
Since this has been fixed upstream in Gutenberg, and ported to trunk, but a Gutenberg release hasn't been made.. I've deactivated Gutenberg on these sites to fix this..
 - Main Network
 - Global Network
 - Make Network
 - Profiles.wordpress.org

The header doesn't need Gutenberg, and is running better without it (due to this bug).

These sites still have Gutenberg enabled, which will cause this problem:
- Learn WordPress - https://learn.wordpress.org
- Testing - https://make.wordpress.org/test-site
- WordPress Developer Resources - https://developer.wordpress.org
- Block Pattern Directory - https://wordpress.org/patterns
- News Theme 2021 Test - https://wordpress.org/news-test

**Comment by dd32** [comment]
Gutenberg 12.5.0 has finally been released, which has brought the fix required to the sites running Gutenberg.
