### ISSUE TITLE
CORS issue with Search field

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-mu-plugins#99]
When the Header is used outside of WordPress, by serving a cached copy of the REST API endpoints, browsers will encounter a CORS issue with the search field button svg.

```
Access to image at 'https://wordpress.org/wp-content/mu-plugins/pub-sync/blocks/global-header-footer/images/search.svg' from origin 'https://codex.wordpress.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

This is because `button.wp-block-search__button` has a `mask-image: url( ...svg )` style applied. When images are used as a mask-image, appropriate CORS headers must be present on the image to allow the browser to load the bitmap of the URL into memory, rather than simply rendering it as a background-image or inline image.

Options:
 - Ensure the image files are served with CORS headers
 - Use `background-image` with `-webkit-filter: invert(100%)`
 - Embed the SVG in the CSS; `-webkit-mask-image: url("data:image/svg+xml;base64,...`
 - (Not an option) Always serve the image from the same domain as the page is rendered on.

Ideally, we'd also serve all of the static images from s.w.org, which also doesn't set CORS headers for SVGs at present. So a solution here may be to ensure s.w.org sets appropriate CORS headers and then move all statics to the CDN.

This is low-priority as it only affects Trac, Codex, and Planet at present. The lack of a visual search button there isn't critical as enter processes the search regardless.

**Comment by ryelle** [comment]
The issue is this icon:
<img width="520" alt="Screen Shot 2022-01-18 at 2 40 57 PM" src="https://user-images.githubusercontent.com/541093/150007123-5ae7e44d-957b-4cce-ba63-3636a75d1278.png">

Another approach could be to switch the form markup to use the "icon search button" and "search button inside" block settings, which would avoid needing to set a background at all (unless the icon is different than the core search, in that case nevermind). I tried it quickly in `try/search-block-settings`: https://github.com/WordPress/wporg-mu-plugins/commit/3d34794c81bd281c4b90c833754cb7262b545137. I think it has promise, and simplifies the CSS a bit, but it needs more work. Could be a starting point for someone post-launch.
